heat_template_version: 2016-10-14
description: 'template to test executing a script with heat'
parameters:
    image:
        type: string
        description: 'image name'
        default: xenial-minimal-cloudimg-amd64-disk1
    keypair:
        type: string
        description: 'keypair name'
        default: mud-key
    flavor:
        type: string
        description: 'flavor name'
        default: ds2G
    message_to_print:
        type: string
        description: 'test messge to print using the script'
        default: 'hello world'
    private_network:
        type: string
        description: 'private network the instance belongs to'
        default: private
    private_net_cidr:
        type: string
        description: 'private network address CIDR notation (a.b.c.d/mask)'
        default: 10.3.0.0/24
    public_network:
        type: string
        description: 'public network the instance belongs to'
        default: public
    private_net_pool_start:
        type: string
        description: 'start IP of the private net pool'
        default: 10.3.0.40
    private_net_pool_end:
        type: string
        description: 'end IP of the private net pool'
        default: 10.3.0.60
    private_net_gateway:
        type: string
        description: 'gateway of the private network'
        default: 10.3.0.1
resources:
    gw_instance:
        type: 'OS::Nova::Server'
        properties:
            flavor: {get_param: flavor}
            key_name: {get_param: keypair}
            image: {get_param: image}
            user_data: |
                #!/bin/sh
                echo "Starting the IDS setup!"
                sudo apt update
                sudo apt install screen -y -q
                screen -dmS ids
                screen -r ids  -X stuff "wget https://raw.githubusercontent.com/charif-mahmoudi/Snorter/master/src/Snorter.sh\n"
                screen -r ids  -X stuff "sudo chmod +x ./Snorter.sh\n"
                screen -r ids  -X stuff "./Snorter.sh -i ens3\n"                
                curl -v http://mud.mocklab.io/snort/up            
            user_data_format: RAW
            networks: [{port: {get_resource: gw_port}}]
    gw_port:
        type: 'OS::Neutron::Port'
        properties:
            network_id: {get_resource: private_net}
    floating_ip:
        type: 'OS::Neutron::FloatingIP'
        properties:
            floating_network_id: {get_param: public_network}
            port_id: {get_resource: gw_port}
    private_net:
        type: 'OS::Neutron::Net'
        properties:
            name: {get_param: private_network}
    private_subnet:
        type: 'OS::Neutron::Subnet'
        properties:
            network_id: {get_resource: private_net}
            cidr: {get_param: private_net_cidr}
            gateway_ip: {get_param: private_net_gateway}
            allocation_pools: [{start: {get_param: private_net_pool_start}, end: {get_param: private_net_pool_end}}]
            dns_nameservers: [10.0.20.200, 8.8.8.8]
            ip_version: 4
    router:
        type: 'OS::Neutron::Router'
        properties:
            external_gateway_info: {network: {get_param: public_network}}
    router_interface:
        type: 'OS::Neutron::RouterInterface'
        properties:
            router_id: {get_resource: router}
            subnet_id: {get_resource: private_subnet}
